version: '3.7'

services:

  gameserver:
    restart: 'always'
    container_name: gameserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 1337:1337